version: '3.3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1240562Na
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1240562Na
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver