server:
  port: 8080
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 1240562Na
    driver-class-name: org.postgresql.Driver
    jpa:
      showsql: true
      database: postgresql
      generate-ddl: false
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        ddl-auto: none
